spring:
  datasource:
    druid:
      url: jdbc:mysql:///vhr?serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
server:
  port: 6666

logging:
  level:
    org.qingqiao.vhr.mapper : debug